#!/usr/bin/python3

from charmhelpers.core.hookenv import action_get
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from charms.layer import snap


def main():
    kwargs = action_get()
    command = kwargs.pop('command', 'install')
    snapname = kwargs.pop('name', None)
    if command == 'remove':
        snap.remove(snapname)
    else:
        getattr(snap, command)(snapname, **kwargs)


if __name__ == '__main__':
    main()
